NHSDigital/reasonable-adjustments-api

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml, proxies/live/apiproxy/proxies/default.xml
=> added splunk callout to proxy

Makefile
=> amb-281: add comment to makefile

ecs-proxies-deploy.yml
=> Amb 180 add health check

azure/azure-release-pipeline.yml
=> enabled monitoring

proxies/live/apiproxy/policies/AssignMessage.AddAsidHeader.xml, proxies/live/apiproxy/policies/AssignMessage.PopulateAsidFromApp.xml, proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml, proxies/live/apiproxy/policies/RaiseFault.400BadRequest.xml, proxies/live/apiproxy/targets/apim.xml
=> added new policies

specification/components/schemas/removerarecord.yaml, specification/reasonable-adjustments.yaml
=> AMB-234 initial draft of endpoint descriptions

azure/azure-release-pipeline.yml
=> AMB-234 make spec visible

specification/reasonable-adjustments.yaml
=> AMB-234 amend technology section

proxies/live/apiproxy/proxies/default.xml
=> AMB-352 fix hardcoded host url

api_tests/tests/reasonable_adjustments/test_asid.py, api_tests/tests/reasonable_adjustments/test_ods.py, proxies/live/apiproxy/targets/apim.xml
=> Amb 363 hotfix asid and ods

api_tests/tests/reasonable_adjustments/test_jwt.py
=> AMB-409 Fixed failing JWT test

specification/reasonable-adjustments.yaml
=> Amb 324 enhance open api spec

azure/azure-release-pipeline.yml
=> AMB-407 execute tests during release pipeline

azure/azure-release-pipeline.yml
=> AMB-407 execute tests during release pipeline for int environment

azure/templates/tests.yml
=> AMB-407 use APIGEE_ENVIRONMENT instead of hardcoded env

api_tests/scripts/authenticator.py, api_tests/tests/reasonable_adjustments/test_happy_cases.py, azure/templates/tests-int.yml
=> AMB-407 run only one test (happy_path)

azure/templates/tests-int.yml
=> AMB-407 remove debug mark

azure/templates/tests-int.yml
=> AMB-407 rename client id and secret

api_tests/steps/check_oauth.py
=> AMB-407 raise exception if couldn't take /token

azure/project.yml, azure/templates/tests-int.yml
=> AMB-407 run tests with debug=true

azure/project.yml, azure/templates/tests-int.yml
=> AMB-407 remove debug lines

api_tests/tests/reasonable_adjustments/test_happy_cases.py, proxies/live/apiproxy/policies/GenerateJWT.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetInteractionID.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetInteractionIDPutConsent.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetInteractionIDPutFlag.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetInteractionIDPutList.xml
=> AMB-430 get scope from kvm

proxies/live/apiproxy/targets/apim.xml
=> AMB-432 move header validation steps to the end of flow

.github/workflows/continous-integration.yaml, .github/workflows/pr-lint.yaml, api_tests/pytest.ini, api_tests/tests/reasonable_adjustments/test_error_cases.py, api_tests/tests/reasonable_adjustments/test_happy_cases.py, azure/templates/tests.yml
=> AMB-359 tag integration tests

azure/azure-release-pipeline.yml, azure/templates/tests-int.yml
=> Readded yaml file to run integration tests on int

azure/azure-release-pipeline.yml, azure/templates/tests-int.yml
=> AMB-463 pass status apikey to release pipeline

api_tests/config_files/environments.py, api_tests/tests/reasonable_adjustment_flag/test_error_cases.py, proxies/live/apiproxy/proxies/default.xml
=> AMB-462 - invalid url validation

specification/components/examples/createConsent.json, specification/components/examples/createFlag.json, specification/components/examples/createList.json, specification/components/examples/updateFlag.json, specification/components/examples/updateList.json
=> Amb 442 delete fhircomment element

api_tests/tests/reasonable_adjustment_flag/test_error_cases.py, proxies/live/apiproxy/proxies/default.xml
=> AMB-470 remove query parameters check condition

api_tests/tests/reasonable_adjustment_flag/test_error_cases.py, api_tests/tests/reasonable_adjustment_flag/test_happy_cases.py, proxies/live/apiproxy/proxies/default.xml
=> AMB-467 add If-Match header to removerarecord

azure/azure-release-pipeline.yml
=> AMB-447 switch release to new reasonable-adjustments-internal-testing

azure/azure-release-pipeline.yml
=> AMB-486 Reinstated INT environment so we can deploy specs

docker/reasonable-adjustment-flag-sandbox/src/mocks/consentGET.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/consentPOST.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/consentPUT.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/flagGET.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/flagPOST.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/flagPUT.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/listGET.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/listPOST.json, docker/reasonable-adjustment-flag-sandbox/src/mocks/listPUT.json, specification/components/examples/createFlag.json, specification/components/examples/createFlagResponse.json, specification/components/examples/createList.json, specification/components/examples/createListResponse.json, specification/components/examples/readListResponse.json, specification/components/examples/readOneFlagResponse.json, specification/components/examples/readTwoFlagResponse.json, specification/components/examples/updateConsent.json, specification/components/examples/updateConsentResponse.json, specification/components/examples/updateFlag.json, specification/components/examples/updateFlagResponse.json, specification/components/examples/updateList.json, specification/components/examples/updateListResponse.json
=> AMB-445 spec review

specification/reasonable-adjustment-flag.yaml
=> AMB-415 add Integration Testing section to spec

.github/workflows/pr-lint.yaml, azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml
=> APM-1351 Pin utils to version with AWS runners

azure/templates/tests-int.yml, azure/templates/tests.yml
=> apm-1351: precreate mounted dirs to ensure agent has rw permissions

api_tests/tests/reasonable_adjustment_flag/test_happy_cases.py, api_tests/tests/request_bank.py, api_tests/tests/utils.py, specification/components/examples/createList.json, specification/components/examples/updateList.json
=> Added tests for /List endpoint

api_tests/README.md, api_tests/steps/check_oauth.py, api_tests/tests/utils.py, manifest_template.yml
=> AMB-568 Made sleep time global and increased timeout for token

proxies/live/apiproxy/policies/KeyValueMapOperations.GetSecureVariables.xml
=> AMB-000 change map identifier from spine to apim

specification/components/examples/createConsentResponse.json, specification/components/examples/createFlagResponse.json, specification/components/examples/createListResponse.json, specification/components/examples/readConsentResponse.json, specification/components/examples/readListResponse.json, specification/components/examples/readOneFlagResponse.json, specification/components/examples/readTwoFlagResponse.json, specification/components/examples/readZeroFlagResponse.json, specification/components/examples/updateConsentResponse.json, specification/components/examples/updateFlagResponse.json, specification/components/examples/updateList.json, specification/components/examples/updateListResponse.json
Updated the example request/responses in the Specification
=> AMB-576:  Spec example updates

api_tests/tests/reasonable_adjustment_flag/test_auth.py, api_tests/tests/reasonable_adjustment_flag/test_error_cases.py, api_tests/tests/reasonable_adjustment_flag/test_proxy.py, api_tests/tests/utils.py, proxies/live/apiproxy/policies/FlowCallout.UserRoleService.xml, proxies/live/apiproxy/targets/ig3.xml
Consuming UserRoleInfo SharedFlow.
=> AMB-563 Implement UserRoleService sharedflow

specification/components/examples/readConsentResponse.json, specification/components/examples/readZeroFlagResponse.json, specification/reasonable-adjustment-flag.yaml
=> Amb 570 ra spec changes

api_tests/.env.sample, azure/project.yml, specification/reasonable-adjustment-flag.yaml
=> AMB-697 Added fhir path

api_tests/tests/reasonable_adjustment_flag/test_error_cases.py, proxies/live/apiproxy/targets/ig3.xml
Hotfix to set up the content-location header only once.
=> AMB-000 Add condition to SetContentLocation policy

api_tests/tests/reasonable_adjustment_flag/test_error_cases.py
=> AMB-643 Added test coverage for user role

specification/reasonable-adjustment-flag.yaml
Made changes to authorisation section and updated the links.
=> Rebrand NHS Identity to NHS CIS2

api_tests/steps/check_oauth.py, api_tests/tests/reasonable_adjustment_flag/test_happy_cases.py
=> AMB-000 fix testing bug

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, manifest_template.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2869
Associating the relevant products that can use mock-oauth with the corrisponding identity-service proxy
=> APM-2869 Associate products with oauth mock idenity service proxy

specification/reasonable-adjustment-flag.yaml
=> fixed broken link and made the link relative

specification/reasonable-adjustment-flag.yaml
Smartcards and HSCN access - clarification
* [x ] Tech Author
=> Smartcards and HSCN access - clarification

specification/reasonable-adjustment-flag.yaml
=> AMB-000 AMP-941 API Specs - add Errors section

specification/reasonable-adjustment-flag.yaml
=> AMB-1513 remove unused schema models

api_tests/tests/reasonable_adjustment_flag/test_happy_cases.py, package-lock.json, package.json
=> AMB-1513 use speccy to resolve rendering bug

manifest_template.yml
=> updated rate limiting to include prod env

docker/reasonable-adjustment-flag-sandbox/src/routes/index.js
=> AMB-1598 bugfix internal-dev-qa hosted container is down

api_tests/tests/reasonable_adjustment_flag/test_proxy.py, api_tests/tests/reasonable_adjustment_flag/test_smoke.py
=> AMB-1598 decouple smoke tests from test-utils

proxies/sandbox/apiproxy/policies/RaiseFault.401Unauthorized.xml, proxies/sandbox/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml, proxies/sandbox/apiproxy/policies/javascript.SetStatusResponse.xml, proxies/sandbox/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/resources/jsc/HealthCheck.SetResponse.js, proxies/sandbox/apiproxy/targets/status.xml
=> AMB-1598 add status endpoin to sandbox

proxies/sandbox/apiproxy/proxies/default.xml
=> AMB-1598 replace duplicated status flow

azure/azure-release-pipeline.yml
=> AMB-1574-Setup-Prod-Pipeline 

azure/azure-release-pipeline.yml, manifest_template.yml
=> AMB-1614-Prod-stage-missing-on-RA 

Makefile, README.md, api_tests/.env.sample, api_tests/Makefile, api_tests/README.md
=> AMB-1410 update readmes

package-lock.json, package.json
=> Amb 000 revert to speccy

api_tests/tests/reasonable_adjustment_flag/test_happy_cases.py, api_tests/tests/request_bank.py, docker/reasonable-adjustment-flag-sandbox/src/mocks/underlyingConditionListPUT.json, docker/reasonable-adjustment-flag-sandbox/src/routes/underlyingConditionListEndpoint.js, proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/proxies/default.xml, pyproject.toml, specification/components/examples/createUnderlyingConditionList.json, specification/components/examples/updateUnderlyingConditionList.json, specification/components/examples/updateUnderlyingConditionListResponse.json, specification/reasonable-adjustment-flag.yaml
=> AMB-1773 add PUT UnderlyingConditionList interaction to proxy

docker/reasonable-adjustment-flag-sandbox/package-lock.json, docker/reasonable-adjustment-flag-sandbox/package.json
=> AMB-000 update inert package for sandbox
